services:
  db:
    image: postgres:14.18
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: db_wallet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: