# Generated by Django 5.2.5 on 2025-08-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('sticker', models.CharField(max_length=6, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_full_name', models.CharField(max_length=100)),
            ],
        ),
    ]
