# Generated by Django 5.2.5 on 2025-08-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker', models.CharField(max_length=6, unique=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WalletConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('stock_date', models.DateField()),
            ],
        ),
    ]
