# Generated by Django 5.2.5 on 2025-08-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="sticker",
            new_name="ticker",
        ),
    ]
