# Generated by Django 5.2.5 on 2025-08-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_sticker_stock_ticker"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="excluded",
            field=models.BooleanField(default=False),
        ),
    ]
