# Generated by Django 5.2.5 on 2025-08-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_walletconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconfig',
            name='id',
            field=models.PositiveSmallIntegerField(
                default=1, primary_key=True, serialize=False),
        ),
    ]
