# Generated by Django 5.2.5 on 2025-09-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_stock_excluded"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoryStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=6, unique=True)),
                ("previous_close", models.FloatField()),
                ("actual_close", models.FloatField()),
                ("alta_baixa", models.FloatField()),
                ("volume", models.FloatField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="walletconfig",
            name="history_date",
            field=models.DateField(default=None),
        ),
    ]
