# Generated by Django 5.2.5 on 2025-09-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_walletconfig_history_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletconfig",
            name="history_date",
            field=models.DateField(default="1900-01-01"),
        ),
    ]
